[package]
name = "storage-api"
version = "0.1.0"
edition = "2024"

[dependencies]
file = {path = "../file"}
page = {path = "../page"}
buffer = {path = "../buffer"}
thiserror.workspace = true

[lints]
workspace = true
