[package]
name = "page"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
paste = { workspace = true }
binary-helpers = { path = "../binary-helpers" }

[lints]
workspace = true